### PR TITLE
[PAXJMS-20] ActiveMQ SSL support

### PR DESCRIPTION
**Pull request by vladimirfx**
Support for setting SSL related properties:
trustStoreType
trustStore
trustStorePassword
keyStoreType
keyStore
keyStorePassword
keyStoreKeyPassword

### CODE REVIEW

**Comment by graben** [comment]
Could you plz create a jira ticket for this and add proper test cases.

**Comment by vladimirfx** [comment]
Yes, sure. But I can’t register in ops4j community - links are broken. Assist please.

**Comment by graben** [comment]
Try at https://ops4j1.jira.com

**Comment by vladimirfx** [comment]
Jira ticket PAXJMS-20

**Pull request merged**
